### PR TITLE
ngx-restangular added

### PR DESCRIPTION
**Pull request by 2muchcoffeecom**

### CODE REVIEW

**Comment by lpolepeddi** [comment]
@2muchcoffeecom Thanks! Ngx-restangular is up on Made with Angular - https://www.madewithangular.com/sites/ngx-restangular

**Comment by 2muchcoffeecom** [comment]
@lpolepeddi thanks for awesome project :)

**Comment by 2muchcoffeecom** [comment]
@lpolepeddi Can you please consider moving ngx-restangular to Developer Tools? It's widely used and has 500+ stars on github https://github.com/2muchcoffeecom/ngx-restangular/stargazers

**Comment by lpolepeddi** [comment]
@2muchcoffeecom Congratulations on your project's popularity! Moved it into the "Developer Tools" category - https://www.madewithangular.com/categories/developer-tools

**Pull request closed without merging**
